version: '3.4'

services:

#### IIS ###################################################
#  aspnetcore_samples:
#    container_name: aspnetcore_samples
### This image  Do not run!!(((
#    image: 'mcr.microsoft.com/dotnet/core-nightly/runtime'

### This image okey, but not volumes((( Try to build this
#    image: 'mcr.microsoft.com/dotnet/core/samples:aspnetapp'


#    build:
#      context: ./dotnet
#      args:
#        - PUID=${PUID:-1001}



#    volumes:
#      - .:/app/wwwroot
#      - ./simplestore:/app/wwwroot
###########Dosn`t_work((((((

#      - ./simplestore/wwwroot:/app/wwwroot/
#      - C:/docker/simplestore/simplestore/wwwroot:/app/wwwroot/
#      - ${PWD}/simplestore/simplestore/wwwroot:/app/wwwroot/
#      - //c/docker/simplestore/simplestore/wwwroot:/code
#    volumes:
#      - type: bind
#        source: ./source_local_directory
#        target: c:\target_directory
#        bind:
#          propagation: cached




#    env_file: .env

#    ports:
#      - "8080:80"
#      - "443:443"

#### Nginx ###################################################
#  nginx:
#    container_name: nginx
#    image: 'nginx:latest'
#    build:
#      context: ./nginx/default
#      args:
#        - PUID=${PUID:-1001}
#    volumes:
#      - ./nginx/default:/opt/nginx
#      - ./nginx/default:/etc/nginx/conf.d/

#    env_file: .env

#    ports:
#      - "8080:80"
#      - "443:443"
### HA Proxy #######################################
  haproxy:
    container_name: haproxy
    image: 'dockercloud/haproxy:latest'
#    links:
#     - nginx
    ports:
      - '80:80'
#    roles:
#      - global
    volumes:
      - ./haproxy:/usr/local/etc/haproxy


### Crontab Container #######################################
#  crond:
#    container_name: crone
#    image: 'flaccid/docker-gc-crond:latest'
#    environment:
#      - HOST_SOURCE=${SERVER_NAME_BASE:-crontab_container}
#    volumes:
#      - /var/run/:/var/run/docker.sock:ro
#
### Volumes Setup ###########################################
#volumes:
#  haproxy:
#    driver: "local"
#  web:
#    driver: "local"

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
